### ISSUE TITLE
GSketchPad

### ISSUE THREAD

**Issue by dackdel** [linux-man/backstage#1]
sketchColor.setGraphic(sketchPg);
line 63 in cp file throws up and error "No library found for processing.awt.PSurfaceAWT
Cannot find a class or type named “GSketchPad”"
im trying to run in in osx high seirrea with 3.5.3 and all the necessary libraries   installed.

**Comment by linux-man** [comment]
I know! :cry: 
It was build with the previous G4P version, which is not compatible with the current version.
I didn't have the time to update (it means to redesign the entire interface), so for now, if you want to run the code you must manually install and use [G4P 4.1.5](https://sourceforge.net/projects/g4p/files/?source=navbar) and [G4P Builder 4.2.1](https://sourceforge.net/projects/guibuilder/files/?source=navbar).
You can check the [talk](https://discourse.processing.org/t/g4p-gui-builder-new-versions-available/7788) with quark.
This issue will remain open until I redo the interface, just to remember.
Sorry for the inconvenience. :anguished:

P.S.: "No library found for processing.awt.PSurfaceAWT" is not a critical error, more like a warning. It should pass.

**Comment by dackdel** [comment]
ah ok no worries. will use 4.1.5 and 4.2.1 and try it out. as long as it works ^^ older or newer library doesn't matter too much for now (for me). Thanks for the reply tho

**Comment by linux-man** [comment]
G4P updated to 4.2.3.
